# Generated by Django 4.1.7 on 2023-04-12 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('text', models.CharField(max_length=255, verbose_name='текст')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='фио')),
                ('pin', models.CharField(max_length=255, verbose_name='пин')),
                ('birthdate', models.DateField(verbose_name='дата рождения')),
                ('grade', models.IntegerField(verbose_name='класс')),
                ('father', models.CharField(max_length=255, verbose_name='отец')),
                ('mother', models.CharField(max_length=255, verbose_name='мать')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.school', verbose_name='школа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='StudentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='student/', verbose_name='фото')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='online_queue.student', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'Фотография студента',
                'verbose_name_plural': 'Фотографии студента',
            },
        ),
        migrations.CreateModel(
            name='OnlineQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms', models.TextField(verbose_name='смс')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='school.school', verbose_name='школа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_queue.student', verbose_name='студент')),
            ],
            options={
                'verbose_name': 'Онлайн очередь',
                'verbose_name_plural': 'Онлайн очередь',
            },
        ),
        migrations.CreateModel(
            name='NewPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='new_photo/', verbose_name='фото')),
                ('news_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_queue.new', verbose_name='фото новостей')),
            ],
            options={
                'verbose_name': 'Новое фото',
                'verbose_name_plural': 'Новые фото',
            },
        ),
    ]
