# Generated by Django 4.1.7 on 2023-03-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinequeue',
            options={'verbose_name': 'Онлайн очередь', 'verbose_name_plural': 'Онлайн очередь'},
        ),
    ]
