# Generated by Django 4.1.7 on 2023-03-11 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyofstudy',
            options={'verbose_name': 'История обучения', 'verbose_name_plural': 'История обучения'},
        ),
    ]
