# Generated by Django 4.1.7 on 2023-03-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Область'},
        ),
    ]
