# Generated by Django 4.1.7 on 2023-03-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_region_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='spots',
            field=models.IntegerField(null=True, verbose_name='свободные места'),
        ),
    ]
