# Generated by Django 4.1.7 on 2023-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_city_name_alter_district_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.IntegerField(null=True, verbose_name='широта'),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.IntegerField(null=True, verbose_name='долгота'),
        ),
    ]
