# Generated by Django 4.1.7 on 2023-03-11 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalfile',
            options={'verbose_name': 'Личное дело', 'verbose_name_plural': 'Личное дело'},
        ),
    ]
