# Generated by Django 4.1.7 on 2023-03-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acievement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldencertificate',
            name='points',
            field=models.IntegerField(verbose_name='баллы'),
        ),
    ]
