# Generated by Django 4.1.7 on 2023-03-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acievement', '0002_alter_goldencertificate_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='olympiad',
            name='points',
        ),
        migrations.AddField(
            model_name='olympiad',
            name='place',
            field=models.IntegerField(null=True, verbose_name='место'),
        ),
    ]
