# Generated by Django 4.1.7 on 2023-03-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_city_name_alter_district_name_and_more'),
        ('acievement', '0002_alter_goldencertificate_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldencertificate',
            name='school_fullname',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='golden', to='school.school', verbose_name='название школы'),
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='school',
            field=models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olympiad', to='school.school', verbose_name='школа'),
        ),
    ]
