# Generated by Django 4.1.7 on 2023-04-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмет',
            },
        ),
        migrations.CreateModel(
            name='PersonalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='prof.profile', verbose_name='профиль')),
            ],
            options={
                'verbose_name': 'Личное дело',
                'verbose_name_plural': 'Личное дело',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='класс')),
                ('personal_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_info', to='personal.personalfile', verbose_name='класс инфо')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_1', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='четверть_1')),
                ('quarter_2', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='четверть_2')),
                ('quarter_3', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='четверть_3')),
                ('quarter_4', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='четверть_4')),
                ('quarter_final', models.IntegerField(choices=[(2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='итоговая')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual', to='personal.grade', verbose_name='годовая')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.subject', verbose_name='предмет')),
            ],
            options={
                'verbose_name': 'Годовая',
                'verbose_name_plural': 'Годовые',
            },
        ),
    ]
